begin;
select plan(12);
select has_table('public','profiles','profiles exists');
select policies_are('public','journal_entries',array['own journal'],'journal only has owner policy');
select policies_are('public','daily_checkins',array['own checkins'],'checkins only has owner policy');
select policies_are('public','relapse_events',array['own relapses'],'relapse plans remain private to their owner');
select policies_are('public','daily_missions',array['own daily missions'],'daily missions only has owner policy');
select policies_are('public','daily_focuses',array['own daily focuses'],'daily focuses only have owner policy');
select policies_are('public','attention_zones',array['own attention zones'],'attention zones only have owner policy');
select policies_are('public','presence_xp_events',array['own presence xp read'],'presence XP is immutable to the user');
select policies_are('public','power_up_logs',array['own power up logs read'],'power-up history is immutable to the user');
select policies_are('public','user_achievements',array['own earned achievements'],'private milestones are readable only by their owner');
select policies_are('public','accountability_relationships',array['owner manages relationship','relationship parties read'],'relationships have explicit policies');
select policies_are('public','support_requests',array['owner creates requests','partner acknowledges requests','relationship parties read requests'],'requests enforce relationship');
select * from finish();
rollback;
