project_id = "sentinel"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]

[db]
port = 55322
shadow_port = 55320
major_version = 17

[studio]
enabled = true
port = 55323

[inbucket]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback"]
enable_signup = true
