"use client";
import { useEffect, useRef, useState, useTransition } from "react";
import { ArrowRight, Check, Copy, Wind } from "lucide-react";
import { finishSOS, startSOS } from "./actions";

const phases = ["pausa","ambiente","respiracao","motivo","alternativa","observar","resultado"] as const;
export function SOSFlow({ motivation, activity }: { motivation?: string; activity?: string }) {
  const [phase, setPhase] = useState(0); const [initial, setInitial] = useState(7); const [finalLevel, setFinalLevel] = useState(4); const [environment, setEnvironment] = useState("Outro"); const [sessionId, setSessionId] = useState<string>(); const [seconds, setSeconds] = useState(600); const [isPending, startTransition] = useTransition(); const startedAt = useRef(0);
  useEffect(() => { if (!sessionId || phase >= 6) return; const id = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(id); }, [sessionId, phase]);
  const notify = (type: "success" | "error", message: string) => window.dispatchEvent(new CustomEvent("sentinel-toast", { detail: { type, message } }));
  const advance = () => { if (phase === 0) { startedAt.current=Date.now(); startTransition(async () => { const result = await startSOS(initial); if (result.success) setSessionId(result.data.id); else notify("error", result.error); setPhase(1); }); } else setPhase((value) => Math.min(phases.length - 1, value + 1)); };
  const finish = () => startTransition(async () => { if (sessionId) { const result=await finishSOS({ id: sessionId, finalIntensity: finalLevel, environment, strategies: ["mudar_ambiente","respiracao","motivacao","atividade_alternativa","urge_surfing"], durationSeconds: Math.round((Date.now() - startedAt.current) / 1000) }); if(result.success&&result.data.levelUp)window.dispatchEvent(new CustomEvent("sentinel-level-up",{detail:{level:result.data.level}})); if(result.success&&result.data.milestoneIds.length)window.dispatchEvent(new CustomEvent("sentinel-milestones",{detail:{milestoneIds:result.data.milestoneIds}})); notify(result.success ? "success" : "error", result.success ? `Protocolo SOS salvo.${result.data.awardedXp ? " +20 XP." : ""}` : result.error); } setPhase(6); });
  const min = String(Math.floor(seconds/60)).padStart(2,"0"), sec = String(seconds%60).padStart(2,"0");
  return <main className="sos-surface grid min-h-screen place-items-center p-5"><div className="w-full max-w-xl"><div className="mb-8 flex items-center justify-between"><span className="sos-accent eyebrow">Modo SOS</span><span className="sos-muted font-mono text-sm">{min}:{sec}</span></div>
    <section className="sos-card rounded-[2rem] border p-6 shadow-2xl sm:p-10">
      {phase === 0 && <><Kicker>Primeiro, uma pausa</Kicker><Title>Você não precisa decidir nada agora.</Title><Text>Vamos criar dez minutos entre o impulso e qualquer decisão. Só precisa dar o próximo passo.</Text><label className="mt-8 grid gap-3 text-sm font-bold">Como está o impulso agora? {initial}/10<input type="range" min="0" max="10" value={initial} onChange={(e)=>setInitial(Number(e.target.value))} className="accent-[#71dbc6]" /></label><Action onClick={advance} disabled={isPending}>{isPending ? "Iniciando..." : "Começar 10 minutos"}</Action></>}
      {phase === 1 && <><Kicker>Quebrar o contexto</Kicker><Title>Saia do ambiente em que você está.</Title><Text>Levante-se. Vá para um lugar aberto ou onde existam outras pessoas. Depois, deixe o celular um pouco mais longe.</Text><label className="mt-8 grid gap-2 text-sm font-bold">Onde você estava?<select value={environment} onChange={(e)=>setEnvironment(e.target.value)} className="sos-select min-h-13 rounded-2xl border px-4">{["Cama","Quarto","Banheiro","Sala","Trabalho","Outro"].map(v=><option key={v}>{v}</option>)}</select></label><Action onClick={advance}><Check size={18}/> Feito</Action></>}
      {phase === 2 && <><Kicker>Respiração</Kicker><div className="mx-auto mt-4 grid size-40 place-items-center rounded-full border border-[#71dbc6]/30 bg-[#71dbc6]/10 motion-safe:animate-pulse"><Wind size={42} className="text-[#71dbc6]" /></div><Title>Inspire 4. Segure 4. Expire 6.</Title><Text>Repita no seu ritmo. Não tente eliminar o impulso; apenas dê espaço para ele diminuir.</Text><Action onClick={advance}>Continuar <ArrowRight size={18}/></Action></>}
      {phase === 3 && <><Kicker>O que importa</Kicker><Title>Você escreveu:</Title><blockquote className="sos-quote display mt-6 border-l-2 border-[#71dbc6] pl-5 text-2xl leading-relaxed">“{motivation ?? "Quero recuperar meu controle e construir uma vida mais presente."}”</blockquote><Action onClick={advance}>Guardar isso comigo</Action></>}
      {phase === 4 && <><Kicker>Uma ação possível</Kicker><Title>{activity ?? "Caminhe por alguns minutos."}</Title><Text>Escolha uma ação física e simples. Mudar o corpo e o ambiente ajuda a interromper o piloto automático.</Text><button onClick={() => navigator.clipboard?.writeText("Estou passando por um momento difícil. Pode falar comigo alguns minutos?")} className="sos-accent mt-7 inline-flex items-center gap-2 text-sm font-bold"><Copy size={16}/> Copiar pedido de apoio</button><Action onClick={advance}>Escolhi minha ação</Action></>}
      {phase === 5 && <><Kicker>Observe sem agir</Kicker><Title>O impulso é uma onda. Você não é a onda.</Title><Text>Perceba onde a sensação aparece no corpo. Observe a intensidade subir, permanecer e começar a passar. Volte à respiração sempre que precisar.</Text><label className="mt-8 grid gap-3 text-sm font-bold">Como está agora? {finalLevel}/10<input type="range" min="0" max="10" value={finalLevel} onChange={(e)=>setFinalLevel(Number(e.target.value))} className="accent-[#71dbc6]" /></label><Action onClick={finish} disabled={isPending}>{isPending ? "Salvando..." : "Concluir protocolo"}</Action></>}
      {phase === 6 && <><Kicker>Você criou espaço</Kicker><Title>{finalLevel < initial ? "O impulso diminuiu." : "Você permaneceu presente."}</Title><Text>O resultado não precisa ser perfeito. Concluir o protocolo já foi uma escolha consciente.</Text><div className="mt-8 grid gap-3 sm:grid-cols-2"><a href="/app/dashboard" className="grid min-h-13 place-items-center rounded-full bg-[#71dbc6] px-6 font-bold text-[var(--ink)]">Estou melhor</a><button onClick={()=>{setPhase(2);setSeconds(300)}} className="min-h-13 rounded-full border border-white/15 px-6 font-bold">Preciso continuar</button></div></>}
    </section></div></main>;
}
function Kicker({children}:{children:React.ReactNode}){return <p className="sos-accent eyebrow">{children}</p>}; function Title({children}:{children:React.ReactNode}){return <h1 className="display mt-4 text-4xl leading-tight sm:text-5xl">{children}</h1>}; function Text({children}:{children:React.ReactNode}){return <p className="sos-muted mt-5 text-lg leading-8">{children}</p>}; function Action({children,onClick,disabled}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button type="button" disabled={disabled} onClick={onClick} className="mt-9 inline-flex min-h-13 w-full items-center justify-center gap-2 rounded-full bg-[#71dbc6] px-6 font-bold text-[var(--ink)] disabled:opacity-50">{children}</button>}
