import Link from "next/link";
import { PageHeader } from "@/components/page-header";
import { SubmitButton } from "@/components/form-controls";
import { createInvite, revokeRelationship, requestSupport } from "@/features/accountability/actions";
import { requireUser } from "@/lib/auth";
import { supportRequestMessages } from "@/lib/support-request-messages";
import { createClient } from "@/lib/supabase/server";

const permissionOptions = [["streak", "Sequência atual"], ["weekly_progress", "Progresso semanal"], ["support_requests", "Pedidos de apoio"], ["checkins", "Check-ins"], ["risk", "Indicador de risco"], ["relapses", "Eventos de recaída"], ["goals", "Metas"], ["journal", "Diário — sensível"]] as const;

export default async function AllyPage({ searchParams }: { searchParams: Promise<{ invite?: string; error?: string; accepted?: string }> }) {
  const user = await requireUser();
  const supabase = await createClient();
  const params = await searchParams;
  const { data: relationships } = await supabase.from("accountability_relationships").select("id,status,invite_email,owner_id,partner_id").or(`owner_id.eq.${user.id},partner_id.eq.${user.id}`).order("created_at", { ascending: false });
  return <div className="mx-auto max-w-4xl p-5 py-8 sm:p-8 lg:p-12">
    <PageHeader eyebrow="Aliado" title="Apoio opcional, limites claros." description="Convide alguém somente se fizer sentido. Você escolhe cada dado compartilhado; diário começa privado." />
    {params.error && <p role="alert" className="mt-6 rounded-2xl bg-red-50 p-4 text-red-800">{params.error}</p>}
    {params.accepted && <p className="mt-6 rounded-2xl bg-emerald-50 p-4 text-emerald-800">Convite aceito. Seu aliado já pode ver somente o que você autorizou.</p>}
    {params.invite && <div className="mt-6 rounded-2xl bg-[#d9eee7] p-5"><p className="text-sm font-bold">Link criado. Ele expira em 7 dias.</p><input readOnly value={params.invite} aria-label="Link de convite privado" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-white px-3 py-2 text-sm" /></div>}
    <form action={createInvite} className="mt-8 grid gap-5 rounded-[1.8rem] bg-white p-6 sm:p-8"><div><h2 className="text-xl font-bold">Convidar um aliado</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">O convite é privado. Você pode revogar acesso quando quiser.</p></div><label className="grid gap-2 text-sm font-bold">E-mail (opcional)<input name="email" type="email" className="min-h-12 rounded-2xl border border-[var(--line)] px-4 font-normal" /></label><fieldset><legend className="text-sm font-bold">Permissões por tipo de dado</legend><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Marque apenas o que seu aliado poderá consultar. Diário permanece desmarcado.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{permissionOptions.map(([key, label]) => <label key={key} className="flex items-center gap-3 rounded-xl border border-[var(--line)] p-3 text-sm"><input type="checkbox" name={key} defaultChecked={["streak", "weekly_progress", "support_requests"].includes(key)} />{label}</label>)}</div></fieldset><SubmitButton>Criar convite privado</SubmitButton></form>
    <div className="mt-6 grid gap-3">{relationships?.map((relationship) => <article key={relationship.id} className="flex flex-col gap-4 rounded-[1.4rem] bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><strong>{relationship.status === "active" ? "Aliado ativo" : relationship.status === "pending" ? "Convite pendente" : "Acesso revogado"}</strong><p className="mt-1 text-sm text-[var(--muted)]">{relationship.invite_email ?? "Convite por link privado"}</p>{relationship.status === "active" && relationship.partner_id === user.id && <Link href={`/app/accountability/${relationship.id}` as never} className="mt-2 inline-block text-sm font-bold text-[var(--teal-deep)]">Ver painel autorizado →</Link>}</div><div className="flex flex-col gap-3 sm:items-end">{relationship.status === "active" && relationship.owner_id === user.id && <form action={requestSupport} className="grid gap-2"><input type="hidden" name="relationshipId" value={relationship.id} /><label className="sr-only" htmlFor={`support-message-${relationship.id}`}>Mensagem de apoio</label><select id={`support-message-${relationship.id}`} name="message" defaultValue={supportRequestMessages[0]} className="min-h-10 rounded-xl border border-[var(--line)] bg-white px-3 text-sm">{supportRequestMessages.map((message) => <option key={message} value={message}>“{message}”</option>)}</select><SubmitButton>Enviar pedido neutro</SubmitButton></form>}{relationship.owner_id === user.id && relationship.status !== "revoked" && <form action={revokeRelationship}><input type="hidden" name="relationshipId" value={relationship.id} /><button className="text-sm font-bold text-red-700">Revogar acesso</button></form>}</div></article>)}</div>
  </div>;
}
