"use client";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, ShieldCheck } from "lucide-react";
import { completeOnboarding } from "./actions";

const goalOptions = ["Parar completamente","Reduzir gradualmente","Entender meus gatilhos","Recuperar o controle","Melhorar meus relacionamentos","Melhorar foco e energia"];
const riskOptions = ["Sozinho","De madrugada","Antes de dormir","Ao acordar","Estressado","Ansioso","Entediado","Triste","Usando redes sociais","No banheiro","Depois de conflitos"];

export function OnboardingFlow({ error }: { error?: string }) {
  const [step, setStep] = useState(1);
  const next = () => setStep((current) => Math.min(8, current + 1)); const back = () => setStep((current) => Math.max(1, current - 1));
  return <main className="min-h-screen bg-[var(--ink)] p-4 text-white sm:p-8"><div className="mx-auto max-w-2xl">
    <header className="flex items-center justify-between py-4"><div className="flex items-center gap-2 font-bold"><ShieldCheck className="text-[#71dbc6]" /> Sentinel</div><span className="text-sm text-white/45">{step} de 8</span></header>
    <div className="mt-5 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-[#71dbc6] transition-all" style={{ width: `${step * 12.5}%` }} /></div>
    {error && <p role="alert" className="mt-6 rounded-2xl bg-red-200 p-4 text-sm text-red-950">{error}</p>}
    <form action={completeOnboarding} className="mt-8 rounded-[2rem] bg-[#f3f7f4] p-6 text-[var(--ink)] shadow-2xl sm:p-10">
      <section hidden={step !== 1}><Kicker>Boas-vindas</Kicker><Title>Este é o seu espaço.</Title><Text>O Sentinel ajuda você a entender padrões, construir hábitos melhores e atravessar momentos difíceis — de forma privada e sem julgamentos.</Text><label className="mt-8 grid gap-2 font-bold">Como prefere ser chamado?<input required name="displayName" autoComplete="given-name" className="min-h-13 rounded-2xl border border-[var(--line)] bg-white px-4 font-normal" /></label></section>
      <section hidden={step !== 2}><Kicker>Seu objetivo</Kicker><Title>O que você deseja mudar?</Title><Text>Você pode escolher mais de uma opção.</Text><ChoiceGrid name="goals" options={goalOptions} /></section>
      <section hidden={step !== 3}><Kicker>Contexto atual</Kicker><Title>Com que frequência isso acontece?</Title><Text>Responder é opcional.</Text><select name="frequency" className="mt-8 min-h-13 w-full rounded-2xl border border-[var(--line)] bg-white px-4"><option value="">Prefiro não responder</option><option>Mais de uma vez por dia</option><option>Diariamente</option><option>Algumas vezes por semana</option><option>Algumas vezes por mês</option><option>Raramente</option></select></section>
      <section hidden={step !== 4}><Kicker>Situações de risco</Kicker><Title>Quando você fica mais vulnerável?</Title><Text>Escolha as situações que mais combinam com sua experiência.</Text><ChoiceGrid name="risks" options={riskOptions} /></section>
      <section hidden={step !== 5}><Kicker>Horários</Kicker><Title>Existe um período que pede mais atenção?</Title><div className="mt-8 grid grid-cols-2 gap-4"><label className="grid gap-2 text-sm font-bold">De<input name="riskStart" type="time" className="min-h-13 rounded-2xl border border-[var(--line)] bg-white px-4" /></label><label className="grid gap-2 text-sm font-bold">Até<input name="riskEnd" type="time" className="min-h-13 rounded-2xl border border-[var(--line)] bg-white px-4" /></label></div></section>
      <section hidden={step !== 6}><Kicker>Motivação</Kicker><Title>Por que você quer mudar?</Title><Text>Esta resposta é privada e poderá aparecer no SOS quando você precisar lembrar do que importa.</Text><textarea required name="motivation" rows={5} placeholder="Quero recuperar meu controle porque..." className="mt-8 w-full resize-none rounded-2xl border border-[var(--line)] bg-white p-4 leading-7" /></section>
      <section hidden={step !== 7}><Kicker>Accountability</Kicker><Title>Você quer alguém acompanhando sua jornada?</Title><Text>Você controla cada permissão. O diário começa sempre privado.</Text><div className="mt-8 grid gap-3">{[["yes","Sim, quero convidar depois"],["later","Talvez mais tarde"],["no","Não agora"]].map(([value,label]) => <label key={value} className="flex min-h-14 items-center gap-3 rounded-2xl border border-[var(--line)] bg-white px-4 font-semibold"><input required type="radio" name="accountability" value={value} />{label}</label>)}</div></section>
      <section hidden={step !== 8}><Kicker>Preferências</Kicker><Title>Deixe o Sentinel do seu jeito.</Title><div className="mt-8 grid gap-4"><Toggle name="discreetMode" title="Modo discreto" text="Usa o nome Focus e reduz textos sensíveis." /><Toggle name="reminders" title="Lembrete diário" text="Notificações sempre usam linguagem neutra." defaultChecked /><label className="grid gap-2 text-sm font-bold">Horário do check-in<input name="checkinTime" type="time" defaultValue="20:00" className="min-h-13 rounded-2xl border border-[var(--line)] bg-white px-4" /></label><label className="grid gap-2 text-sm font-bold">Modo espiritual<select name="spiritualMode" className="min-h-13 rounded-2xl border border-[var(--line)] bg-white px-4 font-normal"><option value="off">Desativado</option><option value="christian">Cristão</option><option value="custom">Personalizado</option></select></label></div></section>
      <div className="mt-10 flex items-center justify-between">{step > 1 ? <button type="button" onClick={back} className="inline-flex min-h-12 items-center gap-2 rounded-full px-4 font-bold text-[var(--muted)]"><ArrowLeft size={18} /> Voltar</button> : <span />}{step < 8 ? <button type="button" onClick={next} className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--ink)] px-6 font-bold text-white">Continuar <ArrowRight size={18} /></button> : <button className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[var(--teal-deep)] px-6 font-bold text-white"><Check size={18} /> Concluir</button>}</div>
    </form>
  </div></main>;
}

function Kicker({ children }: { children: React.ReactNode }) { return <p className="eyebrow text-[var(--teal-deep)]">{children}</p>; }
function Title({ children }: { children: React.ReactNode }) { return <h1 className="display mt-3 text-4xl leading-tight sm:text-5xl">{children}</h1>; }
function Text({ children }: { children: React.ReactNode }) { return <p className="mt-4 leading-7 text-[var(--muted)]">{children}</p>; }
function ChoiceGrid({ name, options }: { name: string; options: string[] }) { return <div className="mt-8 grid gap-3 sm:grid-cols-2">{options.map((option) => <label key={option} className="flex min-h-14 items-center gap-3 rounded-2xl border border-[var(--line)] bg-white px-4 text-sm font-semibold has-[:checked]:border-[var(--teal-deep)] has-[:checked]:bg-[#e6f5f0]"><input type="checkbox" name={name} value={option} />{option}</label>)}</div>; }
function Toggle({ name, title, text, defaultChecked }: { name: string; title: string; text: string; defaultChecked?: boolean }) { return <label className="flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-white p-4"><span><strong className="block">{title}</strong><span className="mt-1 block text-sm leading-5 text-[var(--muted)]">{text}</span></span><input name={name} type="checkbox" defaultChecked={defaultChecked} className="size-5" /></label>; }
