import { Check, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { completePowerUp } from "@/features/daily-missions/actions";

type PowerUp = { id: string; label: string };

export function PowerUpsCard({ powerUps, completedPowerUpIds = [], returnTo = "dashboard" }: { powerUps: PowerUp[]; completedPowerUpIds?: string[]; returnTo?: "dashboard" | "plan" }) {
  const completedIds = new Set(completedPowerUpIds);
  return <section id="power-ups" className="mt-5 rounded-[1.8rem] border border-[var(--line)] bg-white/65 p-6 sm:p-8"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#d9eee7] text-[var(--teal-deep)]"><ShieldCheck size={21} /></span><div><p className="eyebrow text-[var(--teal-deep)]">Equipamento</p><h2 className="display mt-2 text-3xl">Power-ups práticos.</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Conclua uma ação para marcar missão de proteção e registrar +10 XP uma vez hoje.</p></div></div>{powerUps.length ? <ul className="mt-6 grid gap-3 sm:grid-cols-2">{powerUps.map((powerUp) => { const completed = completedIds.has(powerUp.id); return <li key={powerUp.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-white p-4"><strong className="min-w-0 break-words">{powerUp.label}</strong>{completed ? <span className="inline-flex min-h-10 shrink-0 items-center gap-2 rounded-full bg-[#d9eee7] px-4 text-sm font-bold text-[var(--teal-deep)]"><Check size={16} /> Concluído hoje</span> : <form action={completePowerUp}><input type="hidden" name="powerUpId" value={powerUp.id} /><input type="hidden" name="returnTo" value={returnTo} /><button className="primary-action inline-flex min-h-10 shrink-0 items-center gap-2 rounded-full px-4 text-sm font-bold"><Check size={16} /> Concluir</button></form>}</li>; })}</ul> : <div className="mt-6 rounded-2xl bg-[#f3f7f4] p-4 text-sm leading-6 text-[var(--muted)]"><p>Você ainda não cadastrou um power-up.</p><Link href="/app/plan#cadastrar-power-up" className="mt-3 inline-flex font-bold text-[var(--teal-deep)] underline underline-offset-4">Cadastrar meu primeiro power-up</Link></div>}</section>;
}
