"use server";
import { createHash, randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { defaultAccountabilityPermissions } from "@/lib/permissions/accountability";
import { supportRequestMessages } from "@/lib/support-request-messages";

const hash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function createInvite(formData:FormData){const user=await requireUser();const email=z.string().email().optional().safeParse(String(formData.get("email")||"")||undefined);if(!email.success)redirect("/app/accountability?error=Informe%20um%20e-mail%20válido");const token=randomBytes(32).toString("base64url");const permissions=Object.fromEntries(["streak","checkins","risk","relapses","support_requests","weekly_progress","goals","journal"].map((key)=>[key,formData.get(key)==="on"]));defaultAccountabilityPermissions.forEach((key)=>{if(!formData.has(key))permissions[key]=true});const supabase=await createClient();const {error}=await supabase.from("accountability_relationships").insert({owner_id:user.id,invite_email:email.data,invite_token_hash:hash(token),permissions});if(error)redirect("/app/accountability?error=Não%20foi%20possível%20criar%20o%20convite");const url=`${process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000"}/accountability/invite/${token}`;redirect(`/app/accountability?invite=${encodeURIComponent(url)}&toast=Convite%20privado%20criado.`)}
export async function revokeRelationship(formData:FormData){const user=await requireUser();const id=z.uuid().parse(formData.get("relationshipId"));const supabase=await createClient();const{error}=await supabase.from("accountability_relationships").update({status:"revoked",revoked_at:new Date().toISOString()}).eq("id",id).eq("owner_id",user.id);if(error)redirect("/app/accountability?error=Não%20foi%20possível%20revogar%20o%20acesso.");redirect("/app/accountability?toast=Acesso%20revogado%20com%20sucesso.")}
export async function acceptInvite(token:string){const user=await requireUser();const supabase=await createClient();const {error}=await supabase.rpc("accept_accountability_invite",{p_token_hash:hash(token),p_partner_id:user.id});if(error)redirect(`/accountability/invite/${token}?error=Este%20convite%20é%20inválido%20ou%20expirou`);redirect("/app/accountability?accepted=1")}
export async function requestSupport(formData:FormData){const user=await requireUser();const parsed=z.object({relationshipId:z.uuid(),message:z.enum(supportRequestMessages)}).safeParse({relationshipId:formData.get("relationshipId"),message:formData.get("message")});if(!parsed.success)redirect("/app/accountability?error=Escolha%20uma%20mensagem%20de%20apoio.");const supabase=await createClient();const{data:relationship}=await supabase.from("accountability_relationships").select("id,permissions").eq("id",parsed.data.relationshipId).eq("owner_id",user.id).eq("status","active").maybeSingle();if(!relationship||!(relationship.permissions as Record<string,unknown>).support_requests)redirect("/app/accountability?error=Este%20aliado%20não%20tem%20permissão%20para%20receber%20pedidos.");const{error}=await supabase.from("support_requests").insert({relationship_id:relationship.id,owner_id:user.id,message:parsed.data.message});if(error)redirect("/app/accountability?error=Não%20foi%20possível%20enviar%20o%20pedido.");redirect("/app/accountability?toast=Pedido%20de%20apoio%20enviado.")}
